FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PORT=8080

EXPOSE 8080

CMD ["python", "Weather_scrape.py", "--port", "8080"]
